# tasks file for pg

- name: epel-install
  yum:
    name:  
      - nano
      - mc
    state: present

- name: Change repo
  copy:
    src: pgdg-redhat-all.repo
    dest: /etc/yum.repos.d/pgdg-redhat-all.repo

- name: Installing nginx and postgres
  yum:  
    name:  
      - postgresql14-server
      - wget
      - unzip
    state: present 

- name: Initialize PostgreSQL
  shell: "/usr/pgsql-14/bin/postgresql-14-setup initdb"
  tags: 
    - init

    
- name: Change pg_hba
  copy:
    src: pg_hba
    dest: /var/lib/pgsql/14/data/pg_hba.conf 
  become: yes
  become_user: root


- name: Change pg.conf
  copy:
    src: postgresql.conf
    dest: /var/lib/pgsql/14/data/postgresql.conf
  become: yes
  become_user: root
  notify:
    - restart pg


- name: Starting a service
  command: "systemctl start postgresql-14.service "
  become_user: root

- name: Copy a database
  copy:
    src: demo-small-20170815.sql
    dest: /var/lib/pgsql/demo-small-20170815.sql


- name: Change postgres password
  shell: sudo -u postgres psql -c "alter user postgres with encrypted password 'postgres';"
  become: yes
  become_user: root
  tags: change 


- name: Initialize DB
  command: "psql -f /var/lib/pgsql/demo-small-20170815.sql"
  become: yes
  become_user: postgres
  tags: finish




